package com.example.miguel.bludbuwl.player;

public enum Habilidad {

    ATRAPAR("Atrapar","Un jugador con la habilidad Atrapar puede repetir la tirada para atrapar el balón si ha fallado la primera. También permite al jugador repetir la tirada si el balón cae al entregarlo a la mano o no consigue interceptar."),
    ESQUIVAR("Esquivar","Un jugador con la habilidad Esquivar está acostumbrado a zafarse de oponentes y podrá repetir la tirada de esquivar al intentar salir de la zona de defensa de un jugador contrario. Sin embargo, el jugador sólo podrá repetir una tirada de esquivar por turno de equipo. Además, la habilidad Esquivar, si se emplea, afecta al resultado de los dados de Placaje, tal y como se describe en la Reglas de Placaje."),
    MANOSSEGURAS("Manos Seguras","Un jugador con la habilidad Manos Seguras puede repetir el D6 si falla un intento de recoger el balón del suelo. Además, si un jugador contrario tiene la habilidad Robar Balón, no podrá usarla contra un jugador con la habilidad Manos Seguras."),
    PASAR("Pasar","Un jugador con la habilidad Pasar puede repetir la tirada de D6 si realiza un pase fallido o impreciso."),
    PLACAR("Placar","Un jugador con la habilidad Placar es diestro a la hora de derribar jugadores contrarios. La habilidad de Placar, si se usa, afecta a los resultados obtenidos en los dados de Placaje, tal y como se explica en las Reglas de Placaje."),
    SOLITARIO("Solitario","Los solitarios, debido a la inexperiencia, arrogancia, ferocidad animal o simple estupidez, no juegan bien con el resto del equipo. Como resultado, los Solitarios no pueden emplear segundas oportunidades de equipo a menos que primero obtengan un 4+ en un D6. Con un resultado de 1-3 el resultado original se mantiene y la segunda oportunidad se pierde (se usa)."),
    CABEZAHUECA("Cabeza Hueca","El jugador no sobresale por su inteligencia. Por ello, se debe tirar 1D6 después de declarar la acción que realizará el jugador, pero antes de realizarla. Con un resultado de 1 el jugador se quedará parado sin hacer nada, intentando recordar qué debía hacer. El jugador no podrá hacer nada durante el resto del turno y el equipo de ese jugador perderá la acción declarada este turno. (Así, si un jugador con Cabeza Hueca declara un movimiento de Penetración y saca un 1, el equipo no podrá declarar otra Penetración este turno). El jugador pierde su zona de defensa y no podrá atrapar el balón, asistir a ningún jugador en una falta o placaje, o moverse voluntariamente hasta que consiga obtener 2+ al principio de una acción futura o hasta que termine la entrada."),
    GOLPEMORTIFERO("Golpe Mortifero","Suma 1 a los chequeos contra Armadura o para determinar las Heridas causadas por un jugador con esta habilidad cuándo un oponente sea Derribado por este jugador durante un Placaje. Tan sólo puede ser utilizada para modificar una de las tiradas, así que si decides emplear Golpe Mortífero para modificar la tirada de Armadura no podrás modificar la tirada de Heridas."),
    CABEZADURA("Cabeza Dura","Este jugador trata las tiradas de 8 en la Tabla de heridas, después de que se hayan aplicado los modificadores, como un resultado de Aturdido en lugar de Inconsciente. Esta habilidad puede utilizarse incluso si el jugador está Tumbado o Aturdido."),
    LANZARCOMPAÑERO("Lanzar Compañero de Equipo","Un jugador con esta habilidad tiene la capacidad de lanzar a uno de sus compañeros de equipo en lugar del balón. (¡Esto incluye el balón si el jugador lanzado lo tiene en su posesión!). El jugador lanzador debe terminar el movimiento de la Acción de Pase adyacente al compañero de equipo que desea lanzar, el cual deberá tener Agilidad Felina y encontrarse de pie. El pase se resuelve exactamente igual que si el jugador lanzador hiciese un pase, salvo que el jugador debe restar 1 al D6 cuándo pase al jugador y las distancias “Bomba Larga” y “Pase Largo” no son posibles. Además los pases precisos cuentan como pases imprecisos, por esto desvía al jugador tres casillas, ya que los jugadores son más pesados y más difíciles de lanzar que el balón. El jugador lanzado no puede ser interceptado. Un compañero de equipo que resulte “Balón Perdido” caerá en la casilla que ocupaba originalmente. Si el jugador lanzado cae fuera del campo será golpeado por el público de la misma manera que un jugador que es empujado al público. Si la casilla final sobre la que se desvía está ocupada por otro jugador, trata al jugador que se encontraba en ella como Derribado y tira su Armadura (incluso si ya estaba Tumbado o Aturdido) y entonces se desviará una casilla más. Si el jugador lanzado vuelve a caer sobre otro jugador, continúa desviándolo hasta que caiga en una casilla vacía o fuera del campo (es decir, no puede aterrizar sobre más de un jugador). Mira la descripción de Agilidad Felina para ver si el jugador aterriza sobre sus pies ¡o cabeza abajo sobre sus maltrechos huesos!"),
    PASESEGURO("Pase Seguro","El jugador es un experto lanzando el balón de tal forma que hace incluso más difícil a cualquier oponente interceptarlo. Si un pase realizado por este jugador es interceptado, entonces el jugador con Pase Seguro puede hacer una tirada de agilidad sin modificar. Si tiene éxito la intercepción queda anulada y la secuencia de pase continuará con normalidad."),
    FURIA("Furia","Un jugador con esta habilidad es un sangriento psicópata que ataca a sus oponentes con una rabia incontrolable. A menos que se indique lo contrario, esta habilidad deberá emplearse siempre. Cuándo realice un placaje, un jugador con esta habilidad siempre seguirá si puede. Si obtiene un resultado de “Empujado” o “Defensor Cede”, el jugador tiene que realizar inmediatamente un nuevo placaje contra el oponente siempre y cuándo permanezcan de pie y adyacentes. Si le es posible, el jugador también seguirá este segundo placaje. Si el jugador con Furia está realizando una acción de Penetración deberá hacer el segundo placaje a menos que no tenga más movimiento y no pueda ir A Por Ellos de nuevo."),
    CUERNOS("Cuernos","Un jugador con cuernos puede utilizarlos para golpear a los jugadores adversarios. Esto le permite sumar 1 a su Fuerza al llevar a cabo un Placaje. Sin embargo, el jugador sólo puede utilizar esta habilidad mientras esté efectuando una Acción de Penetración y si al menos ha movido una casilla antes de efectuar el Placaje (¡no cuenta levantarse al inicio de su acción!). Si el jugador tiene la habilidad Furia, entonces el modificador se aplica en el segundo placaje si se ha aplicado en el primero."),
    ANIMALSALVAJE("Animal Salvaje","Los animales salvajes son criaturas incontrolables que rara vez hacen lo que el entrenador les pide. De hecho, de lo único que puedes estar seguro que harán es sacudir a los jugadores contrarios que se acerquen mucho a ellos. Para representar esto, cuándo declares una acción con un Animal Salvaje, tira 1D6, añadiendo 2 a la tirada si es una Acción de Placaje o Penetración. Con un resultado de 1 a 3, el animal salvaje permanecerá donde está, rugirá de rabia y la acción se perderá."),
    PASEPRECIPITADO("Pase Precipitado","Esta habilidad permite al jugador efectuar un Pase Rápido cuándo un jugador contrario declare que lo va a placar, pudiendo así librarse del balón antes de ser placado. El pase debe resolverse mediante el procedimiento habitual antes de que el jugador del equipo contrario resuelva su placaje. Deben aplicarse las reglas de pase, con la excepción de que ningún equipo sufre un cambio de turno a causa del resultado de este pase, sea cual sea. Después de que se resuelva el pase, tu oponente realiza el placaje y sigue adelante con su turno. Pase Precipitado no puede usarse en el segundo placaje de oponente con la habilidad Furia o en combinación con las habilidades Bombardero o Lanzar Compañero de Equipo."),
    PERSEGUIR("Perseguir","El jugador puede emplear esta habilidad cuándo un jugador del equipo contrario que esté realizando una Acción salga de su zona de defensa por cualquier razón. Cada entrenador tirará un dado y sumará el atributo Movimiento de su jugador. Si el jugador perseguidor obtiene un resultado igual o superior al del jugador perseguido, éste podrá mover a la casilla que ha dejado vacía el jugador perseguido. Al efectuar este movimiento no deberá efectuarse ninguna tirada para Esquivar y el hacerlo no afectará en ninguna forma a su movimiento el siguiente turno. Si el jugador perseguidor obtiene una tirada inferior a la del jugador perseguido, el jugador deberá permanecer en su casilla. Un jugador puede efectuar todos los movimientos de persecución que desee. Si un jugador abandona la zona de defensa de varios jugadores con la habilidad Perseguir, sólo uno de los jugadores podrá tratar de perseguirlo."),
    PUÑAL("Puñal","Un jugador con esta habilidad está armado con algo útil a la hora de apuñalar, cortar o rajar a un contrario, como colmillos afilados o una fiel daga. El jugador puede atacar a un oponente apuñalándolo en lugar de realizar un placaje contra él. Haz una tirada sin modificadores contra la Armadura de la víctima. Si el resultado es menor o igual que la Armadura de la víctima entonces no tendrá efecto alguno. Si el resultado supera el valor de Armadura de la víctima, habrá resultado herida y deberá realizarse una tirada de heridas. La tirada de heridas ignorará todos los modificadores aplicables, incluyendo los de Heridas Permanentes y Escurridizo. Si esta habilidad se emplea como parte de una Acción de Penetración, el jugador no podrá seguir moviendo después de utilizarla. Las lesiones causadas por un apuñalamiento no otorgan Puntos de Estrellato."),
    ENPIEDEUNSALTO("En pie de un salto","Un jugador con esta habilidad puede reincorporarse rápidamente al juego. Si el jugador declara cualquier Acción que no sea una Acción de Placaje puede levantarse sin emplear los tres puntos de movimiento. El jugador puede también declarar una Acción de Placaje mientras se encuentra tumbado, lo que requiere una tirada de Agilidad de con un modificador de +2 para ver si puede realizar la acción. Una tirada exitosa permite al jugador levantarse gratuitamente y placar a un oponente adyacente. Una tirada fallida significa que la Acción de Placaje se pierde y el jugador no podrá levantarse."),
    NERVIOSDEACERO("Nervios de Acero","El jugador puede ignorar los modificadores por zonas de defensa contrarias al intentar efectuar un Pase, Atrapar o Interceptar."),
    ECHARSEAUNLADO("Echarse a un lado","Un jugador con esta habilidad es un experto en apartarse del camino de sus atacantes. Para representar esta habilidad, su entrenador puede elegir a qué casilla se retirará cuándo sea empujado, en lugar del entrenador contrario. Además, el entrenador puede elegir cualquier casilla adyacente al jugador, no tan sólo las tres casillas especificadas en el diagrama de desplazamiento. Ten en cuenta que el entrenador puede elegir la casilla a la que es empujado, incluso si el jugador es empujado y derribado."),
    CARRERA("Carrera","El jugador puede intentar moverse hasta tres casillas adicionales en vez de las dos habituales al realizar un movimiento de “A por Ellos” (ver página 20). Tendrá que efectuar la tirada para determinar si cae en cada casilla adicional a la que entre."),
    MANTENERSEFIRME("Mantenerse Firme","Un jugador con esta habilidad puede elegir no ser empujado como resultado de un Placaje. Puede ignorar los resultados “Empujado” y los resultados que derriben al jugador siempre lo derribarán en la misma casilla en la que se encuentre. Si un jugador es empujado contra un jugador con Mantenerse Firme, ninguno de los dos jugadores se moverá."),
    BRAZOFUERTE("Brazo Fuerte","El jugador puede sumar 1 al resultado del D6 cuándo realiza un Pase Corto, Pase Largo o Bomba Larga."),
    ECHARRAICES("Echar Raices","Inmediatamente después de declarar una Acción con este jugador, tira un D6. Con un 2 o más el jugador podrá realizar la acción normalmente. Con un 1, el jugador “echa raíces” y su movimiento será considerado de 0 hasta que termine la entrada, quede tumbado o resulte derribado (y no, ¡no pueden intentar placarlo jugadores de su propio equipo para derribarlo!). Un jugador que haya Echado Raíces no puede Ir A Por Ellos, ser empujado por ninguna razón o utilizar cualquier habilidad que le permita moverse de la casilla en la que se encuentra o ser colocado tumbado. El jugador puede placar a jugadores adyacentes pero sin seguirlos como parte de una Acción de Placaje, pero si el jugador no supera la tirada de Echar Raíces y estaba realizando una Acción de Penetración no podrá placar ese turno (aunque podrá tirar para levantarse si estaba tumbado)."),
    SALTAR("Saltar","Un jugador con la habilidad Saltar puede intentar saltar a cualquier casilla vacía, a 2 casillas de distancia como máximo, aunque tenga que pasar sobre una casilla ocupada por un jugador de cualquier equipo. Saltar le cuesta al jugador dos puntos de Movimiento. Para efectuar el salto, mueve al jugador a una casilla vacía a 1 ó 2 casillas de distancia de su casilla actual y efectúa una tirada de Agilidad. No se aplican modificadores a esta tirada de D6 a menos que el jugador tenga Piernas Muy Largas. El jugador no tiene que esquivar para abandonar la casilla en la que estaba. Si el jugador supera la tirada, podrá saltar sin ningún problema y seguir moviéndose. Si falla la tirada de Agilidad caerá al suelo en la casilla a la que estaba intentando saltar. El entrenador contrario efectuará una tirada contra Armadura para determinar si ha resultado herido. Si falla el salto habrá un cambio de turno y el turno del equipo que estaba moviendo terminará inmediatamente. Un jugador sólo puede utilizar la habilidad Saltar una vez por Acción."),
    PLACAJEDEFENSIVO("Placaje Defensivo","Esta habilidad niega a los jugadores adversarios, situados en su zona de defensa, la posibilidad de utilizar su habilidad Esquivar al intentar salir de la zona de defensa de un jugador, o en caso de ser placado por el jugador que cuenta con esta habilidad."),
    PIESFIRMES("Pies Firmes","El jugador puede repetir el D6 si resulta derribado mientras está intentando ir “A Por Ellos” (ver página 20). Un jugador sólo puede utilizar la habilidad Pies Firmes una vez por turno."),
    AGALLAS("Agallas","Un jugador con esta habilidad es capaz de convencerse de que puede enfrentarse al más fuerte de los adversarios. Esta habilidad sólo funciona cuándo el jugador intenta placar a un jugador contrario más fuerte que él. Al utilizar esta habilidad, el entrenador del jugador con la habilidad Agallas tira un D6 y suma su Fuerza. Si el resultado de la tirada es inferior o igual a la Fuerza del contrario, el jugador con Agallas tendrá que utilizar su Fuerza normal en el Placaje. Si el total es mayor que el atributo de Fuerza del contrario, la Fuerza del jugador con Agallas se considerará igual a la del contrario en ese Placaje. La fuerza de ambos jugadores se calcula antes de aplicar cualquier modificador por apoyos defensivos u ofensivos pero después de todos los demás modificadores."),
    ABRIRSEPASO("Abrirse Paso","El jugador puede utilizar su Fuerza en vez de su Agilidad cuándo realiza una tirada de Esquivar. Por ejemplo, un jugador con Fuerza 4 y Agilidad 2, al realizar una tirada de esquivar utilizaría un valor de Agilidad 4. Esta habilidad sólo puede ser utilizada una vez por turno."),
    JUEGOSUCIO("Juego Sucio","Un jugador con esta habilidad ha entrenado a conciencia durante mucho tiempo para aprender todas las formas de juego sucio conocidas. Añade 1 a cualquier tirada de Armadura o de Heridas hecha por un jugador con esta habilidad cuándo realice una Falta como parte de una Acción de Falta. Ten en cuenta que tan sólo puedes modificar una de las tiradas de dado, así que si decides emplear Juego Sucio para modificar la tirada de Armadura, no podrás modificar también la tirada de Heridas."),
    JUGGERNAUT("Juggernaut","Un jugador con esta habilidad es virtualmente imparable una vez comienza a moverse. Si el jugador realiza una Acción de Penetración, los jugadores contrarios no podrán emplear sus habilidades Zafarse, Mantenerse Firme o Forcejeo contra sus placajes y puede tratar el resultado “Ambos Derribados” como si hubiese obtenido un resultado de “Empujado” en el dado de Placaje."),
    SINMANOS("Sin Manos","El jugador es incapaz de recoger, interceptar o llevar el balón y fallará cualquier tirada de atrapar automáticamente, ya sea porque literalmente no tenga manos o porque las tenga ocupadas. Si intenta recoger el balón del suelo, rebotará y se producirá un cambio de turno si es el turno de su equipo."),
    ARMASECRETA("Arma Secreta","Algunos jugadores están armados con equipo especial denominado “armas secretas”. Aunque las reglas de Blood Bowl prohíben específicamente el uso de cualquier arma, el juego tiene una larga historia de equipos que han intentado emplear armas de algún tipo. Sin embargo, el uso de armas secretas es claramente ilegal, y los árbitros tienen la desagradable costumbre de expulsar a los jugadores que las utilizan. Una vez termine una entrada en la que el jugador haya participado en cualquier momento, el árbitro ordena que sea expulsado a la mazmorra para que se una a los jugadores a los que cogieron haciendo faltas durante el partido sin importar que el jugador estuviese todavía en el campo o no."),
    AGILIDADFELINA("Agilidad Felina","Un jugador con esta habilidad puede ser lanzado por un jugador de su equipo que tenga la habilidad Lanzar Compañero de Equipo. Mira la habilidad Lanzar Compañero de Equipo más adelante para obtener detalles sobre cómo se lanza a un jugador. Cuándo un jugador con esta habilidad es lanzado o resulta “Balón Perdido” y termina en una casilla vacía, deberá realizar una tirada de aterrizaje. Una tirada de aterrizaje es una tirada de Agilidad con un -1 por cada zona de defensa contraria que afecte a la casilla en la que intenta aterrizar. Si supera la tirada aterriza sobre sus pies. Si falla la tirada o aterriza sobre otro jugador durante el lanzamiento, se coloca Tumbado y se realiza una tirada contra Armadura, para ver si resulta herido. Si el jugador no resulta herido durante el aterrizaje, podrá realizar una Acción en el turno si no ha realizado ninguna todavía. Una tirada de aterrizaje fallida o aterrizar en el público no causa cambio de turno, a menos que el jugador tuviese el balón en su poder."),
    ESCURRIDIZO("Escurridizo","El jugador es tan pequeño que es muy difícil atraparlo, ya que es capaz de pasar por debajo de los brazos extendidos de los contrarios que intentan agarrarlo y colarse entre sus piernas. Por otro lado, los jugadores Escurridizos son demasiado pequeños como para lanzar bien el balón. Para representar esto, los jugadores Escurridizos al efectuar las tiradas para Esquivar, pueden ignorar las zonas de defensa de las casillas a las que moverá (o sea, es como si siempre tuviera un modificador final de +1 a Esquivar), pero deben restar 1 a la tirada cuándo realizan un pase. Además, añade 1 a cualquier Tirada de heridas que se realice contra un jugador con la habilidad Escurridizo. Los jugadores escurridizos equipados con un Arma Secreta no podrán ignorar las zonas de defensa contrarias, pero sufrirán las penalizaciones."),
    BOMBARDERO("Bombardero","Un entrenador puede decidir que un Bombardero, que no se encuentre Tumbado o Aturdido, lance una bomba en vez de efectuar cualquier otra Acción. No cuenta como la Acción de Pase del equipo. La bomba se lanza siguiendo el mismo procedimiento que para lanzar el balón (incluido el efecto del Tiempo), a excepción de que el jugador no podrá moverse ni ponerse de pie antes de lanzar la bomba (¡necesita tiempo para prender la mecha!). Los pases interceptados con la bomba no causan cambio de turno. Los pases perdidos o cualquier explosión que lleven a un jugador del equipo activo a ser derribado se consideran cambio de turno. Todas las habilidades que pueden emplearse cuándo se pasa el balón pueden emplearse cuándo se lanza una bomba. La bomba puede ser interceptada o atrapada, empleando las mismas reglas que al atrapar el balón en cuyo caso, el jugador que la ha atrapado tiene que lanzarla inmediatamente. Esta es una acción adicional que tiene lugar fuera de la secuencia normal de juego. Un jugador que tenga el balón puede intentar atrapar o interceptar y lanzar una bomba. La bomba explota cuándo aterriza en una casilla vacía o se falla o se declina el intentar atraparla (las bombas no “rebotan”). Si la bomba resulta “balón perdido” explotará en la casilla del lanzador. Si la bomba cae en el público explotará sin efecto alguno. Cuándo la bomba por fin explota, cualquier jugador en la misma casilla que la bomba resulta Derribado y los jugadores de casillas adyacentes serán Derribados con un resultado de 4+. Los jugadores pueden resultar alcanzados por una bomba incluso si ya se encontraban Tumbados o Aturdidos y deberán ser tratados como si los acabasen de Derribar igualmente. Realiza tiradas de Armadura y Heridas por los jugadores a los que Derribó la bomba. Las lesiones causadas por una bomba no otorgan puntos de estrellato."),
    SIERRAMECANICA("Sierra Mecanica","Un jugador armado con una sierra mecánica tiene que atacar con ella en lugar de realizar un placaje cuándo realiza una Acción de Placaje o de Penetración. Cuándo se emplea la sierra mecánica para realizar un ataque, tira un D6 en lugar del dado de Placaje. Con un resultado de 2 o más la sierra mecánica golpea al jugador pero con un resultado de 1 rebota y ¡en lugar de eso golpea a su portador! Realiza una tirada de Armadura por el jugador que resulte golpeado por la motosierra, añadiendo 3 al resultado. Si la tirada supera la armadura de la víctima, el jugador resulta Derribado y herido; tira en la tabla de Heridas. Si la tirada no consigue superar la armadura de la víctima, el ataque no tendrá efecto. Un jugador armado con una sierra mecánica puede realizar una Acción de Falta y añadir 3 a la tirada de Armadura, pero debe tirar por si rebota como se describe más atrás. Una Sierra Mecánica en funcionamiento es algo muy peligroso, así que si un jugador que tenga una sierra mecánica resulta Derribado por cualquier razón, el entrenador contrario podrá añadir 3 a su tirada de Armadura para ver si el jugador resulta herido. Sin embargo, placar a un jugador con una sierra mecánica es igualmente peligroso, si un oponente se derriba a si mismo al placar a un jugador con sierra mecánica se añade 3 a su tirada de armadura. Esta habilidad sólo puede emplearse una vez por turno (p.ej.: no puede emplearse con Furia o Placaje Múltiple) y si se utiliza como parte de una Acción de Penetración, el jugador no podrá seguir moviendo tras emplearla. Las lesiones causadas por una Sierra Mecánica no otorgan Puntos de Estrellato."),
    BOLACONCADENA("Bola con Cadena","Los jugadores armados con una Bola con Cadena sólo pueden realizar acciones de Movimiento. Para moverse o ir A Por Ellos, coloca la plantilla de devolución del balón sobre el jugador apuntando a la parte inferior o superior del campo o hacia cualquiera de las dos bandas. Después tira un D6 y mueve al jugador a la casilla indicada; no será necesario esquivar al salir de una zona de defensa. Si el jugador acaba fuera del campo, será atacado por el público como cuándo se empuja a un jugador fuera del campo. Repite este proceso hasta que el jugador se quede sin movimiento (puedes ir A Por Ellos si así lo deseas). Si durante su Acción de movimiento el jugador entra en una casilla ocupada por un jugador contrario o aliado, el jugador realizará un placaje (¡incluso si tienen Apariencia Asquerosa!). Los jugadores Tumbados o Aturdidos son empujados y se realizará una tirada de Armadura para ver si resultan heridos, en lugar de realizar un placaje contra ellos. Si empuja a otro jugador, deberá ocupar la casilla que éste dejó y seguir con su movimiento como ya se ha descrito. Si el jugador con la Bola con Cadena resulta Derribado o queda Tumbado tira inmediatamente para heridas (no se requerirá tirada de Armadura). Los resultados de Aturdido en la tirada de Heridas se considerarán Inconscientes. Un jugador con Bola con Cadena puede utilizar la habilidad Apartar (como si realizase una Acción de Placar) cuándo realiza un placaje (¡si es que la ha aprendido!). Un jugador con Bola con Cadena jamás puede utilizar las habilidades Placaje Heroico, Furia, Anticiparse, Saltar, Bloquear Pase o Perseguir."),
    PIERNASMUYLARGAS("Piernas muy Largas","El jugador puede añadir 1 a la tirada de D6 cada vez que intente interceptar o utilice la habilidad Saltar. Además, la habilidad Pase Seguro no puede emplearse en las intercepciones realizadas por este jugador."),
    SIEMPREHAMBRIENTO("Siempre Hambriento","El jugador siempre se encuentra ferozmente hambriento ¡y podría comerse cualquier cosa! Por ello, cada vez que el jugador use la habilidad Lanzar compañero de Equipo, tira 1D6 después de que halla terminado de moverse, pero antes de lanzar al jugador. Si el resultado es un 1, tratará de comerse al desafortunado compañero de equipo. Tira 1D6 otra vez, un segundo 1 indicará que ha conseguido engullir al jugador, lo que lo matará sin posibilidad de salvarse (no se puede emplear ni Médico, ni Regenerar ni ninguna otra cosa). Si el jugador llevaba el balón, rebotará desde la casilla del jugador lanzado. Si el resultado es de 2 a 6, el jugador consigue liberarse y la acción se tratará como si fuese un “balón perdido” del jugador. Resuelve el “balón perdido” de manera normal con el jugador con la habilidad Agilidad Felina."),
    REALMENTEESTUPIDO("Realmente Estupido","El jugador es sin duda una de las criaturas más estúpidas que haya pisado un campo de Blood Bowl (¡Qué considerando el CI de la mayor parte de los jugadores, es decir mucho!). Por ello debes tirar 1D6 después de declarar la acción que realizará el jugador, pero antes de realizarla. Si hay uno o más jugadores de su mismo equipo de pie adyacentes al jugador Realmente Estúpido y no son también Realmente Estúpidos, añade 2 a la tirada de dado. Con un resultado de 1-3 el jugador se quedará sin hacer nada, intentando recordar lo que debía hacer. El jugador no podrá hacer nada más durante el turno y el equipo perderá la acción que había declarado durante ese turno (así que, si un jugador Realmente Estúpido declara una Acción de Penetración y saca un 1, el equipo no podrá declarar otra Acción de Penetración este turno). El jugador pierde su zona de defensa y no podrá interceptar, pasar o atrapar el balón, asistir a ningún jugador en una falta o placaje, o moverse voluntariamente hasta que consiga superar una tirada de Realmente Estúpido al principio de una acción futura o termine la entrada."),
    REGENERACION("Regeneracion","Si el jugador sufre un resultado de Lesión en la tabla de Heridas, tira 1D6 para regenerar después de tirar en la tabla de Lesiones y después de cualquier tirada de Médico, de realizarse. Con un resultado de 1-3, el jugador sufrirá el resultado de la herida. Con uno de 4-6, el jugador curará la herida después de un corto período de tiempo para “reorganizarse” a sí mismo y se coloca en la zona de Reservas. Las tiradas de Regeneración no pueden repetirse. Recuerda que los jugadores contrarios seguirán ganando Puntos de Estrellato normalmente por causar una Lesión a un jugador con esta habilidad, aunque el resultado no afecte al jugador de la forma normal."),
    COLAPRENSIL("Cola Prensil","El jugador tiene una cola larga y gruesa que puede utilizar para zancadillear a los jugadores adversarios. Para representar esto, los jugadores adversarios deberán restar 1 al D6 cuándo estén intentando esquivar al jugador para salir de su zona de defensa."),
    DEGENERAR("Degenerar","Permanecer en el campo es difícil cuándo tu cuerpo está en descomposición y apenas se mantiene unido. Cuándo este jugador sufra un resultado de Lesión en la Tabla de heridas, tira dos veces en la Tabla de lesiones (ver página 27) y aplica ambos resultados. El jugador sólo se perderá un partido como resultado de sus lesiones, aunque obtenga dos resultados con este efecto."),
    GARRAS("Garras","Un jugador esta habilidad ha sido bendecido con una gran pinza o garras o afilados espolones que hacen las armaduras inútiles. Cuándo derribe a un oponente como resultado de un placaje, cualquier tirada de Armadura de 8 o más después de modificar, pasará automáticamente la armadura."),
    PRESENCIAPERTURBADORA("Presencia Perturbadora","El aspecto del jugador es muy perturbador ya sea por causa de una enorme nube de moscas, expulse almizcle soporífero, un aura de caos aleatorio, frío intenso o una feromona que cause miedo y pánico. Al margen de la naturaleza de esta mutación, cualquier jugador debe restar 1 al D6 cuándo pase, intercepte o atrape por cada jugador contrario con Presencia Perturbadora que se encuentre a tres casillas de él incluso si el jugador con Presencia Perturbadora se encuentra Tumbado o Aturdido."),
    PUTREFACCIONDENURGLE("Putrefaccion de Nurgle","Este jugador tiene una horrible enfermedad infecciosa que se extiende cuándo mata a un jugador durante una Acción de Placaje, Penetración o Falta. En lugar de morir de verdad, el jugador queda infectado y se transforma en un Putrefacto novato. Para poder hacer esto, el oponente debe haberlo borrarlo de la hoja de equipo durante el paso 2.1 de la Secuencia Posterior al encuentro, su Fuerza no puede ser mayor que 4 y no puede tener las habilidades Degeneración, Regeneración o Escurridizo. El nuevo Putrefacto puede ser incluido gratuitamente en el equipo de Nurgle durante el paso 6 de Actualizar la hoja de equipo si el equipo tiene espacio para él. Este nuevo Putrefacto cuenta con todo su valor a la hora de calcular el valor del equipo de Nurgle."),
    APARIENCIAASQUEROSA("Apariencia Asquerosa","El aspecto físico del jugador es tan horrible que cualquier jugador que quiera placarle (o utilizar un ataque especial en lugar del placaje) deberá obtener previamente un resultado de 2 o más en 1D6. Si el resultado obtenido es un 1, su estómago estará demasiado revuelto como para intentar el placaje y perderá el mismo (aunque su equipo no sufrirá un cambio de turno)."),
    TENTACULOS("Tentaculos","El jugador puede utilizar esta habilidad cuándo un jugador contrario trate de abandonar su zona de defensa. Cada entrenador tira un D6 y añade la FU de su jugador a la tirada. El jugador contrario añade 1 a su tirada. Si el resultado del jugador con esta habilidad es superior al del jugador que trataba de moverse, el jugador que trataba de moverse habrá sido agarrado firmemente por los tentáculos del jugador y no podrá abandonar a casilla en la que se encuentra ni moverse más. Si un jugador abandona la zona de defensa de varios jugadores con esta habilidad, tan sólo uno de ellos podrá intentar agarrarlo con sus tentáculos."),
    CANIJO("Canijo","Los jugadores canijos tienden a ser incluso más pequeños y enclenques que los jugadores Escurridizos. Para representar esto, el jugador puede añadir 1 a las tiradas de Esquivar que intente. Por otro lado, aunque los contrarios tienen que seguir esquivando para salir de las zonas de defensa de los jugadores canijos, son tan pequeños que no ejercen el modificador de -1 cuándo un contrario esquiva a cualquiera de sus zonas de defensa."),
    SEDDESANGRE("Sed de Sangre","Los Vampiros deben, de vez en cuándo, alimentarse de la sangre de los vivos. A causa de esto, tira 1D6 cada vez que declares una Acción con un Vampiro. Con un resultado de 2+, el jugador podrá seguir realizando la acción normalmente. Con un 1, el jugador es superado por el deseo de beber sangre Humana y deberá realizar la siguiente Acción especial: El Vampiro pierde la acción declarada ese turno (también el equipo Vampiro) y deberá realizar una Acción de Movimiento. Si el Vampiro termina su movimiento de pie y adyacente a uno o más Siervos que se encuentren de pie, derribados o aturdidos, de su propio equipo, atacará a uno de ellos. Tira inmediatamente para herir al Siervo que ha sido atacado, sin realizar tirada de Armadura. La herida no causará cambio de turno a menos que el Siervo tuviese el balón. Si el Vampiro no puede atacar a un Siervo (por cualquier razón), se retirará del campo y será colocado en la zona de Reservas y su equipo sufrirá un cambio de turno. Si tenía el balón, rebotará desde la casilla en la que se encontraba cuándo fue retirado del campo y no podrá anotar un touchdown (incluso si llega a la línea de touchdown antes de ser retirado). Si el Vampiro resulta Herido o queda Inconsciente antes de atacar a un Siervo, entonces deberá ser colocado en la zona adecuada del Banquillo en lugar de en la zona de Reservas. Recuerda que el jugador puede recoger el balón o realizar cualquier otra cosa que pudiera hacer normalmente cuándo se realiza una Acción de Movimiento, pero debe morder a un Siervo para evitar el cambio de turno."),
    MIRADAHIPNOTICA("Mirada Hipnotica","El jugador tiene una poderosa habilidad telepática, que puede utilizar para dejar a un jugador rival completamente inmóvil. El jugador puede utilizar la Mirada Hipnótica al final de su Acción de Movimiento contra un jugador contrario en una casilla adyacente. Realiza una tirada de Agilidad por el jugador con mirada hipnótica, con un modificador de –1 por cada zona de defensa contraria que afecte al jugador y no sea la de la victima. Si la tirada de agilidad resulta exitosa, la víctima queda hipnotizada y pierde su zona de defensa y no podrá atrapar el balón, asistir a ningún jugador en una falta o placaje o moverse voluntariamente hasta el inicio de su siguiente acción o fin de la entrada. Si la tirada de Agilidad no resulta exitosa, la mirada hipnótica no tendrá efecto."),
    NINGUNA(" "," ");

    private String nombreHabilidad;
    private String descripcion;

    Habilidad(String nombreHabilidad, String descripcionHabilidad) {
        this.nombreHabilidad = nombreHabilidad;
        this.descripcion = descripcionHabilidad;
    }

    public String getNombre() {
        return nombreHabilidad;
    }

    public String getDescripcion() {
        return descripcion;
    }
}
